name: Update README with Recent Activity
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "ACTIVITY_LOG"
          feed_list: "https://github.com/VertigoFromOuterSpace.atom"
          max_post_count: 5
          template: "- $date: $title<br>" # <-- A MUDANÇA ESTÁ AQUI
          date_format: "yyyy-mm-dd HH:MM"
